version: '3.8'
services:
  spring-blue:
    container_name: timo-repo-blue
    image: menten4859/timo-repo:latest
    restart: always
    ports:
      - "8081:8080"     # API (Blue)
      - "8085:8085"     # Socket.IO (Blue)
    networks:
      - timo-network

  timo-redis:
    container_name: timo-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - timo-network

networks:
  timo-network:
    driver: bridge
