version: '3.8'
services:
  timo-redis:
    container_name: timo-redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - timo-network

networks:
  timo-network:
    driver: bridge
    name: timo-network  # 외부 네트워크로 사용
