version: '3.8'
services:
  spring-blue:
    container_name: timo-repo-blue
    image: menten4859/timo-repo:latest
    restart: always
    ports:
      - "8080:8080"     # API (Blue)
      - "8085:8085"     # Socket.IO (Blue)
    networks:
      - timo-network

networks:
  timo-network:
    external: true
