version: '3.8'
services:
  spring-green:
    container_name: timo-repo-green
    image: menten4859/timo-repo:latest
    restart: always
    ports:
      - "8082:8080"     # API (Green)
      - "8086:8085"     # Socket.IO (Green)
    networks:
      - timo-network

networks:
  timo-network:
    external: true
